FROM python:3.12-slim@sha256:a6e34c598f2467ed0e9a8d349809fcd8b5c603269512df273a0bb1784edc11b1

WORKDIR /app

COPY app/requirements-outscale.txt .
RUN pip install --no-cache-dir -r requirements-outscale.txt

COPY app/vm_power_outscale.py .

ENTRYPOINT ["python", "vm_power_outscale.py"]
