FROM python:3.12-slim

WORKDIR /app

COPY app/requirements-outscale.txt .
RUN pip install --no-cache-dir -r requirements-outscale.txt

COPY app/vm_power_outscale.py .

ENTRYPOINT ["python", "vm_power_outscale.py"]
