name: Docker build and publish gitlab-runner

on:
  push:
    paths:
      - 'gitlab-runner/**'
      - '.github/workflows/**'
  workflow_dispatch:
  schedule:
  # every day
  #  - cron: '0 1 * * *'
  # weekly
    - cron: '0 0 * * 0'

env:
  REGISTRY: ghcr.io
  REGISTRY_BASE_PATH: ghcr.io/${{ github.repository }}
  IMAGE_NAME: ghcr.io/${{ github.repository_owner}}/gitlab-runner

jobs:
  build:
    name: Build and publish docker images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@900f2210b1d28bbbd0bd22d17926b9e224e8f231

      - name: Calculate docker image tag
        id: set-tag
        run: |
          git fetch -t
          tag=$( git describe --tags --always)
          echo "$tag"
          echo "tag=$tag" >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}

      - name: Build and push
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
        with:
          context: gitlab-runner
          tags: "${{ env.IMAGE_NAME }}:${{ steps.set-tag.outputs.tag }}, ${{ env.IMAGE_NAME }}:latest"
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
          push: true
