#
# generate Docker images for cluster-api-provider-outscale for development and testing purposes
#
name: Docker build and publish cluster-api-provider-outscale

on:
  push:
    paths:
      - '.github/workflows/build-cluster-api-provider-outscale*'
  workflow_dispatch:
    commitref:
      description: 'branch, tag or SHA to checkout'
      default: 'main'
      required: true
      type: string
  schedule:
  # weekly
    - cron: '0 0 * * 0'
env:
  REGISTRY: ghcr.io
  REGISTRY_BASE_PATH: ghcr.io/${{ github.repository_owner }}

jobs:
  build:
    name: Build and publish images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout outscale/cluster-api-provider-outscale code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: 'outscale/cluster-api-provider-outscale'
          ## change default tag
          ref: ${{ inputs.commitref }}
          path: 'capi-outscale'

      - name: Calculate docker image tag
        id: set-tag
        run: |
          ( cd capi-outscale
          git fetch -t
          tag=$(git describe --tags --always)
          echo "tag=$tag" >> $GITHUB_OUTPUT
          )
      - uses: oras-project/setup-oras@v1
      - run: oras version

      - name: Build OCI artifact for provider components
        run: |
          ( cd capi-outscale
            bash -c "make release"
            find out -type f
          ) || exit 1
          ( cd capi-outscale/out
            echo "build oci artifact"
            oras push --oci-layout cluster-api-outscale-components:${RELEASE_TAG} metadata.yaml infrastructure-components.yaml cluster-template.yaml
            find cluster-api-outscale-components -type f
          ) || exit 1
        env:
          VERSION: ${{ steps.set-tag.outputs.tag }}
          TAG: ${{ steps.set-tag.outputs.tag }}
          RELEASE_TAG: ${{ steps.set-tag.outputs.tag }}
          REGISTRY: ${{ env.REGISTRY_BASE_PATH }}

      - name: Docker build
        run: |
          ( cd capi-outscale
             bash -c "make docker-build"
          )
        env:
          VERSION: ${{ steps.set-tag.outputs.tag }}
          TAG: ${{ steps.set-tag.outputs.tag }}
          REGISTRY: ${{ env.REGISTRY_BASE_PATH }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker push
        run: |
          ( cd capi-outscale
             bash -c "make docker-push"
          )
        env:
          VERSION: ${{ steps.set-tag.outputs.tag }}
          TAG: ${{ steps.set-tag.outputs.tag }}
          REGISTRY: ${{ env.REGISTRY_BASE_PATH }}
      - name: OCI artifact push
        run: |
          ( cd capi-outscale/out
            oras cp --from-oci-layout cluster-api-outscale-components:${RELEASE_TAG} ${REGISTRY}/cluster-api-outscale-components:${RELEASE_TAG}
          )
        env:
          VERSION: ${{ steps.set-tag.outputs.tag }}
          TAG: ${{ steps.set-tag.outputs.tag }}
          RELEASE_TAG: ${{ steps.set-tag.outputs.tag }}
          REGISTRY: ${{ env.REGISTRY_BASE_PATH }}
