name: Docker build and publish helmfile

on:
  push:
    paths:
      - 'helmfile/**'
      - '.github/workflows/**'
  workflow_dispatch:
  #schedule:
  # every day
  #  - cron: '0 1 * * *'
  # weekly
  #  - cron: '0 0 * * 0'

permissions: {}

env:
  REGISTRY: ghcr.io
  REGISTRY_BASE_PATH: ghcr.io/${{ github.repository }}
  IMAGE_NAME: ghcr.io/${{ github.repository_owner}}/helmfile

jobs:
  prepare:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    outputs:
      versions: ${{ steps.versions.outputs.versions }}
      short_sha: ${{ steps.sha.outputs.short_sha }}

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
        with:
          persist-credentials: false

      - name: Load versions
        id: versions
        run: |
          echo "versions=$(jq -R -s -c 'split("\n")[:-1]' helmfile/versions.txt)" >> "$GITHUB_OUTPUT"

      - name: Compute short SHA
        id: sha
        run: |
          echo "short_sha=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

  build:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        helmfile_version: ${{ fromJson(needs.prepare.outputs.versions) }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
        with:
          persist-credentials: false

      - name: Login to GitHub Container Registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
        with:
          context: helmfile
          platforms: linux/amd64
          push: true
          build-args: |
            DOCKER_HELMFILE_VERSION=${{ matrix.helmfile_version }}
          tags: |
            ${{ env.IMAGE_NAME }}:${{ matrix.helmfile_version }}-${{ needs.prepare.outputs.short_sha }}
